# This workflow builds the AYAB AppImage Installer and stores it as an artifact

name: AppImage Build

on:
  push:
    branches:
      - '*-appimage'

jobs:
  build:
    # oldest LTS version still supported
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        image: ['1', '2010', '2014']
        arch: ['x86_64', 'i686']
        tag: [cp27-cp27m, cp27-cp27mu, cp35-cp35m, cp36-cp36m, cp37-cp37m,
              cp38-cp38]
        exclude:
          - image: '2014'
            tag: cp27-cp27m
          - image: '2014'
            tag: cp27-cp27mu

    steps:
      # checkout repo under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
      with:
        # recursively checkout submodules
        submodules: recursive
        # checkout all history
        fetch-depth: 0
    - name: Set GIT_TAG variable
      run: |
        echo "::set-env name=GIT_TAG::$(git describe --tags)"
    - name: Set PACKAGE_VERSION
      run: |
        echo ${{env.GIT_TAG}} > src/main/resources/base/ayab/package_version
        sed -i 's/PACKAGE_VERSION/${{env.GIT_TAG}}/' src/build/settings/base.json
        cat src/main/resources/base/ayab/package_version
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        # architecture 'x86' or 'x64'
        architecture: x64
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # pip install -r linux-build\appimage_build_requirements.txt
    - name: Convert PyQt5 `.ui` files and create translation files
      run: |
        ./setup_environment.sh
    - name: Download and execute tools to build AppImage
      run: |
        # wget -nv -c https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage
        wget -nv -c https://github.com/niess/python-appimage/releases/download/python3.7/python3.7.8-cp37-cp37m-manylinux2010_x86_64.AppImage
        # chmod +x appimagetool-x86_64.AppImage
        chmod +x python3.7.8-cp37-cp37m-manylinux2010_x86_64.AppImage
        ARCH=x86_64 ./python3.7.8-cp37-cp37m-manylinux2010_x86_64.AppImage appimage/ayab 
    - name: Build the appimage
      run: |
        # Build the AppImage
        python -m python_appimage build manylinux \
          ${{ matrix.image }}_${{ matrix.arch }} ${{ matrix.tag }}
        # Export the AppImage name and the Python version
        appimage=$(ls python*.AppImage)
        SCRIPT=$(cat <<-END
        version = '${appimage}'[6:].split('.', 2)
        print('{:}.{:}'.format(*version[:2]))
        END
        )
        version=$(python -c "${SCRIPT}")
        echo "::set-env name=PYTHON_APPIMAGE::${appimage}"
        echo "::set-env name=PYTHON_VERSION::${version}"
    - name: Build app
      run: |
        python -m fbs freeze --debug
    - name: Create installer
      run: |
        python -m fbs installer
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: AYABSetup-${{env.GIT_TAG}}
        path: target/AYABSetup.exe
